version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
      - '8080:80'
    volumes:
      - data1:/website:/usr/local/apache2/htdocs

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - data2:/data
    environment:
      - MINIO_ROOT_USER: ${APPUSER}
      - MINIO_ROOT_PASSWORD: ${SECRET}
      - MINIO_DEFAULT_BUCKETS: default
  db:
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - data3:/var/lib/mysql
    environment:
      - MYSQL_USER: ${APPUSER}
      - MYSQL_PASSWORD: ${SECRET}
      - MYSQL_ROOT_PASSWORD: ${SECRET}
      - MY_SQL_DATABASE: mydatabase
     		
volumes:
    data1:
    data2:
    data3:
