services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    restart: 'always'
    ports:
      - '8080:80'
    volumes:
      - web_data:/usr/local/apache2/htdocs

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${APPUSER}
      MYSQL_PASSWORD: "${SECRET}"
      MYSQL_ROOT_PASSWORD: "${SECRET}"
      MYSQL_DATABASE: mydatabase

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: 'always'
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${APPUSER}
      MINIO_ROOT_PASSWORD: ${SECRET}
      MINIO_DEFAULT_BUCKETS: mybucket

volumes:
  web_data:
  minio_data:
  db_data:
